[workspace]
resolver = "2"
members = ["generator"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
askama = "0.12"
clap = { version = "4.4", features = ["derive"] }
rand = "0.8"
